- name: "Add Node.js from source"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" | sudi -E bash -
- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes